### ISSUE TITLE
用C++改写后，性能如何？

### ISSUE THREAD

**Issue by fxsjy** [yanyiwu/cppjieba#1]
你好，我是结巴分词的作者，请问cppjieb的分词速度如何？

**Comment by logicxin** [comment]
cppjieba使用大的字典（367w）， 我主要使用计算关键词抽取，速度变的很慢。请问有什么优化策略？

**Comment by lzzgeo** [comment]
抱歉啊，我没再关注了，对于分词，我没做过深入研究哈
------------------------------------------------------------------发件人：LOGIC <notifications@github.com>发送时间：2018年3月27日(星期二) 14:57收件人：yanyiwu/cppjieba <cppjieba@noreply.github.com>抄　送：sam <lzzgeo@aliyun.com>; Mention <mention@noreply.github.com>主　题：Re: [yanyiwu/cppjieba] 用C++改写后，性能如何？ (#1)
cppjieba使用大的字典（367w）， 我主要使用计算关键词抽取，速度变的很慢。请问有什么优化策略？—
