### ISSUE TITLE
能否提供一个编译好的C语言的结巴DLL

### ISSUE THREAD

**Issue by k39k39** [yanyiwu/cppjieba#102]
需要在DELPHI中调用，但在https://github.com/yanyiwu/cjieba 里下载的代码多次尝试生成DLL失败，希望大大提供一下。

**Comment by cgoxopx** [comment]
好像这个库对Windows支持不好吧

**Comment by k39k39** [comment]
DLL做好了，使用OK，现在的问题是，如果词库较大，测试40M以上的文件，就经常在初始化加载时newjieba，发生错误，不知道其他朋友有没有遇到过，怎么处理的。
