### ISSUE TITLE
分词输出乱码且分词速度慢

### ISSUE THREAD

**Issue by lenghonglin** [yanyiwu/cppjieba#116]
![tim 20180721132902](https://user-images.githubusercontent.com/4686802/43032556-7328430e-8cec-11e8-8bc2-a8a7b277f654.png)
 输出乱码，参照了该https://github.com/yanyiwu/cppjieba/issues/62     修改，仍输出乱码，并且分词一次的大概需要30S左右。

**Comment by lenghonglin** [comment]
找到输出乱码的问题了，被https://github.com/yanyiwu/cppjieba/issues/62  给误导了，看了这个回答把文件编码改为了UTF-8，控制台始终输出乱码，今天看了下，控制台只能输出GB2312的编码，并且不能修改，于是把文件编码改回了GB2312，就能正常输出了。
一句话总结，GB2312编码没问题的，没必要转UTF-8。但是现在还有个问题就是加载字典的速度太慢了，需要30S才能加载完成，还不知道是哪儿的问题

**Comment by cgoxopx** [comment]
我加载字典也慢

**Comment by lenghonglin** [comment]
@cgoxopx   VS要改为release模式，debug模块很慢的
