### ISSUE TITLE
现在的buffer大小是多少？

### ISSUE THREAD

**Issue by snakecy** [yanyiwu/cppjieba#119]
现在的buffer大小是多少？
是include/cppjieba/Trie.hpp这个中const size_t MAX_WORD_LENGTH = 512的大小？是的话可否设置为2048？

**Comment by Ozal220** [comment]
> 现在的buffer大小是多少？
> 是include/cppjieba/Trie.hpp这个中const size_t MAX_WORD_LENGTH = 512的大小？是的话可否设置为2048？

这个问题我也想知道，当处理一个字数很多的文件时该如何处理？
