### ISSUE TITLE
如何训练和更新hmm_model.utf8

### ISSUE THREAD

**Issue by chenrulongmaster** [yanyiwu/cppjieba#122]
如何训练和更新hmm_model.utf8?

**Comment by PierreZhangcw** [comment]
@chenrulongmaster 
这里没有训练和更新hmm_model的代码。可以在网上找到，比如[https://www.cnblogs.com/chen8023miss/p/11977224.html](https://www.cnblogs.com/chen8023miss/p/11977224.html)。我自己有进行过尝试，尝试成功。

注意事项：
- 首先是对参数的保存，需要先观察cppjieba中hmm_model.utf8的格式，然后自己写一个参数保存的方法。
- cppjieba的hmm模型中，不包含对标点符号的标签标注以及预测，所以要注意在发射矩阵中不要包含状态对标点符号字符的相关发射概率。否则cppjieba载入hmm_model.utf8时会报错。

**Comment by chenrulongmaster** [comment]
> @chenrulongmaster
> 这里没有训练和更新hmm_model的代码。可以在网上找到，比如https://www.cnblogs.com/chen8023miss/p/11977224.html。我自己有进行过尝试，尝试成功。
> 
> 注意事项：
> 
> * 首先是对参数的保存，需要先观察cppjieba中hmm_model.utf8的格式，然后自己写一个参数保存的方法。
> * cppjieba的hmm模型中，不包含对标点符号的标签标注以及预测，所以要注意在发射矩阵中不要包含状态对标点符号字符的相关发射概率。否则cppjieba载入hmm_model.utf8时会报错。

老铁，你这个有点6了
