### ISSUE TITLE
对于英文的话，支持自定义的词组吗，把多个英文单词绑定在一起来分词？

### ISSUE THREAD

**Issue by romanticss** [yanyiwu/cppjieba#136]
多个英文单词，空格分隔导入自定义词表无效，替换为其他词后，会导致英文切分错误

**Comment by limingxinleo** [comment]
这个你是怎么处理的呢？

@romanticss

**Comment by romanticss** [comment]
> 这个你是怎么处理的呢？
> 
> @romanticss

两个方法：1. 源码里面是基于空格切分了，导致英文词组无效，所以需要改源码
2. 比较简单，把英文词组的空格转化为特殊字符即可，所以使用的时候需要转化回来
