### ISSUE TITLE
能否像python一样，只划分用户自定义词典里面包含的词，其余词划分成单个字

### ISSUE THREAD

**Issue by cooooooder** [yanyiwu/cppjieba#147]

**Comment by catqaq** [comment]
请关闭hmm和规则部分即可（目前jieba中二者是耦合在一起的），因此关闭hmm即可纯基于词典进行最大概率分词

**Comment by catqaq** [comment]
请关闭hmm和规则部分即可（目前jieba中二者是耦合在一起的），因此关闭hmm即可纯基于词典进行最大概率分词
