### ISSUE TITLE
MixSegment无法切分 英文+中文 组合词

### ISSUE THREAD

**Issue by tuang** [yanyiwu/cppjieba#24]
直接调用MixSegment， 导入词典是 jieba.dict.utf8与hmm_modle.utf8；输入“B超 T恤”，返回结果是["B", "超", " T", "恤"]；
可是python版结巴是ok的；想问问这是为什么？抑或是我哪打开方式不对？
谢谢～

**Comment by GoXian** [comment]
> @tuang 谢谢你的反馈，这个确实有一点小trick（或者可以算是小bug吧），这段时间工作比较忙，拖到今天才有空完善了一下，不好意思。
> 
> 现在已经ok了。你更新一下master的代码。

我发现 U盘 这个词也会被拆成 U 盘（我使用的版本是V5.0.3）

**Comment by GoXian** [comment]
> > @tuang 谢谢你的反馈，这个确实有一点小trick（或者可以算是小bug吧），这段时间工作比较忙，拖到今天才有空完善了一下，不好意思。
> > 现在已经ok了。你更新一下master的代码。
> 
> 我发现 U盘 这个词也会被拆成 U 盘（我使用的版本是V5.0.3）

我已经在dict里面添加了这个词，解决了 ”U盘“ 这个词的问题。
