### ISSUE TITLE
独立出 jiebalib 的建议

### ISSUE THREAD

**Issue by falood** [yanyiwu/cppjieba#25]
最近想基于 cppjieba 写一个 Erlang 的接口 ，发现如下问题
1. std_outbound.hpp 中 <tr1/unordered_map> 依赖问题
2. cppjieba 中集成了多种格式编码的字典文件、web服务器及 daemon script 等模块

所以暂时用 nodejieba 的代码构建了项目。
因此有以下建议：

独立出一个最小化的 jiebalib 项目，去除依赖，只提供引擎功能

**Comment by huangjiahong0601** [comment]
请问下，怎么配置libcppjieba到之前的cppjieba-master中呢？

**Comment by huangjiahong0601** [comment]
请问下，怎么配置libcppjieba到之前的cppjieba-master中呢？

**Comment by huangjiahong0601** [comment]
请问下，怎么配置libcppjieba到之前的cppjieba-master中呢？

**Comment by aijianiula0601** [comment]
libcppjieba怎么配置到cppjieba-master呢？
