### ISSUE TITLE
HTTP接口是否支持批处理？

### ISSUE THREAD

**Issue by masayoshi-louis** [yanyiwu/cppjieba#46]
因为我不希望对每一句话都调用一次。

**Comment by tianliang0123** [comment]
你的意思是http接口中处理多句话，还是该程序是否支持处理一个文本文件，即给定一个文件如example.txt，然后想让此程序直接返回example-token.zh？问题不太明确？

**Comment by masayoshi-louis** [comment]
我指的是HTTP，比如post一个列表（一批句子），服务端一次性处理完这些句子然后同样返回一个列表。

**Comment by lua9520** [comment]
3
