### ISSUE TITLE
请问是否能够提供词性标注的使用示例？

### ISSUE THREAD

**Issue by MaloLK** [yanyiwu/cppjieba#48]
这个链接https://github.com/aszxqw/cppjieba/blob/master/test/tagging_demo.cpp已经失效。

**Comment by MaloLK** [comment]
issue #32 中的演示代码运行后，没有输出，不知是什么原因。

**Comment by MaloLK** [comment]
issue #32 有演示代码。

**Comment by yanyiwu** [comment]
@MaloLK 词性标注请看这里： https://github.com/yanyiwu/cppjieba/blob/master/test/demo.cpp#L38

话说那个失效的链接是你从哪找到的呢？那个链接早就该失效了。

**Comment by MaloLK** [comment]
在issue #32 中作者你自己在后面标注了这个参考链接。
