### ISSUE TITLE
考虑把cppjieba的server部分独立出来，只留和分词相关的核心代码，轻装上阵。

### ISSUE THREAD

**Issue by yanyiwu** [yanyiwu/cppjieba#51]
rt

**Comment by yanyiwu** [comment]
https://github.com/yanyiwu/cppjieba/pull/52

**Comment by xiangzhai** [comment]
非常感谢你的libcppjieba ;-) https://github.com/xiangzhai/kjieba

**Comment by yanyiwu** [comment]
@xiangzhai 赞，遇到什么问题希望多反馈。多谢！

**Comment by yanyiwu** [comment]
已完成，如果仍然需要分词HTTP服务的请移步到新仓库： https://github.com/yanyiwu/cppjieba-server
