### ISSUE TITLE
增加windows ci 测试 windows环境的兼容性

### ISSUE THREAD

**Issue by yanyiwu** [yanyiwu/cppjieba#55]

**Comment by yanyiwu** [comment]
没找到windows开发环境的自动化测试服务。。。作罢。。

**Comment by qinwf** [comment]
Windows 设置起来很麻烦，Appveyor 可以。我在 Appveyor 上的 CI 是使用别人的准备好的镜像。

https://github.com/krlmlr/r-appveyor 

https://github.com/krlmlr/r-appveyor/blob/master/scripts/appveyor-tool.ps1

**Comment by yanyiwu** [comment]
Thanks so much!

**Comment by yanyiwu** [comment]
感谢 @qinwf 的 pr：https://github.com/yanyiwu/cppjieba/pull/63
