### ISSUE TITLE
Hi yanyiwu, how about making a branch for c++11 or c++14

### ISSUE THREAD

**Issue by cypro666** [yanyiwu/cppjieba#56]
you known , so much good stuffs in c++11 and c++14, like lambda expression, you'll omit 
static bool compare(const X&....) { .................. return ..} instead, `[ ](X x, Y y){return x < y;}`
maybe less code?

std::unordered_map and std::unordered_set also better choise than TR1.....

**Comment by yanyiwu** [comment]
If all the c++ production environment has been upgrade to c++11, the world of c++ coder would be awesome.
But in our world, I have to make cppjieba backwards-compatible with the older c++ compiler .

Creating a branch for c++11 has too much works to do. I have not enough time to do it all by myself, 
I hope someone else help me to do it.
