### ISSUE TITLE
inconsistent with jieba raw python version, seems less accurate

### ISSUE THREAD

**Issue by psy2013GitHub** [yanyiwu/cppjieba#57]
string s = "附近可点击开飞机的科技开发的开放的了骄傲的龙卷风房贷款及付3的即可看见空间打开"
**## python version: jieba.posseg.cut **
       附近 f
可 v
点击 v
开 v
飞机 n
的 uj
科技开发 nt
的 uj
开放 v
的 uj
了 ul
骄傲 a
的 uj
龙卷风 nr
房 n
贷款 n
及 c
付 v
3 m
的 uj
即可 d
看见 v
空间 n
打开 v

**## cppjieba version tag**
附近 f
可 v
点击 v
开 v
飞机 n
的 uj
科技开发 nt
的 uj
开放 v
的 uj
了 ul
骄傲 a
的 uj
龙卷风 nr
房 n
贷款 n
及付 x
3 x
的 uj
即可 d
看见 v
空间 n
打开 v

**## inconsistent lies in number 3**

**Comment by yanyiwu** [comment]
谢谢反馈。
老实说，cppjieba对词性标注的支持目前不太好，需要依赖词性标注的建议还是使用 jieba分词吧。

**Comment by psy2013GitHub** [comment]
嗯。
