### ISSUE TITLE
当读入20M以上的文件时 分词出错，关键词抽取出错！

### ISSUE THREAD

**Issue by 381930260** [yanyiwu/cppjieba#61]
当读入20M以上的文件时 分词出错，关键词抽取出错！
string s length: 14490184
[demo] CutAll
_count: 390
_words.size: 390

[demo] KEYWORD
2016-04-15 14:43:13 ../include/cppjieba/KeywordExtractor.hpp:79 ERROR words illegal

**Comment by yanyiwu** [comment]
1. 什么叫20M以上的文件？是词典还是输入的句子？
2. 你把那20M的文件发给我吧，我来试试，可能是中文编码问题。你确定那20M文件都是utf8编码的吗？
加我qq 64162451传给我，或者直接发我QQ邮箱也可以。

**Comment by 381930260** [comment]
我错了。。我忘了转编码了~！对不住了！

**Comment by aeromomo** [comment]
问问题前能多想想吗，你知道你浪费了多少人多少秒时间吗
