### ISSUE TITLE
windows下如何编译？

### ISSUE THREAD

**Issue by cdj0311** [yanyiwu/cppjieba#62]

**Comment by yanyiwu** [comment]
这个问题太尖锐了。之前不少issue都是关于windows上使用cppjieba的，有成功案例，但是我没有试过，我都是mac+linux开发环境，只能希望哪个好心人给搞一发windows使用cppjieba的录制视频终结此类issue吧。

**Comment by qinwf** [comment]
我试着写了 Windows MSVC 的 CI 脚本，待会推上来看看。

**Comment by aeromomo** [comment]
为什么不用mac or linux呢？Gcc g++就好了。花5秒钟。另外你还要setup整个环境？

**Comment by swigger** [comment]
我在vc上用得好好的。没什么特别问题。注意编码保持utf-8.

**Comment by frederickMaster** [comment]
@swigger 你好 打扰下。代码移植到windows下VS2010  但是无法进行正确的切分， 需要注意什么问题 麻烦指点一下。

**Comment by swigger** [comment]
你需要先把字符串都转化为utf-8再去调用切分。vc默认的是gbk的。你可以用 MultiByteTowidechar先把 gbk转成unicode，再用widechartomultibyte转化为utf-8。如果你需要printf出来的时候，你需要再把utf-8转化为gbk。

当然，你应该写两个小函数来帮助你从复杂的转来转去中解放出来。
string gbk2utf8(const string & src){....}
string utf82gbk(const string & src){....}
代码我就不贴了，就是调前面说的那两个函数。

另外，需要检查一下cpp jieba的头文件中有没有直接用到汉字，如果有，那些代码要改。

对于我而言，我把vc的编译器直接修改了，所有的字符串都会被vc认为是utf-8的，而不是gbk，所以我不需要担心头文件中有没有字符串。但是你需要。

我修改vc编译器的目的是为了让vc跟gcc行为保持一致，这样可以给我带来很多方便。

**Comment by ImaginationWork** [comment]
我用 cmake 很轻松就编译过去了，运行良好。 用的是 VS2015 。

**Comment by txhwutu** [comment]
vs里编译不成功或者运行不成功的可以按照这个设置试试https://msdn.microsoft.com/en-us/library/mt708821.aspx   ，控制台输出乱码的话可以在main()的开始加上SetConsoleOutputCP(65001)

**Comment by YuliyaLi** [comment]
@swigger 你好 请问如何修改vs编译器为utf-8?试了https://msdn.microsoft.com/en-us/library/mt708821.aspx 不成功, 期待您的回复，谢谢!

**Comment by swigger** [comment]
对于vs2017 直接用参数 /source-charset:utf-8 /execution-charset:utf-8  。注意不要用/utf-8，好像无效。
vs2015没有试过。vs2013或更低版本没有参数，需要hack编译器内部函数，不建议使用（我以前是用这种方式）。

**Comment by wangzhe258369** [comment]
有一个可选择的方式是用TDM-GCC-64

**Comment by TangMonk** [comment]
mingw按理说是可以编译Linux下编写的C++项目的，cppjieba是编译成功了，但是demo.exe和test跑步起来

**Comment by Skifary** [comment]
vs如果遇到Trie.hpp相关的编译错误，是因为Trie.hpp包含中文注释并且是utf8编码的格式，vs使用非uft8编码的时候会出现编译错误
