### ISSUE TITLE
search mode 的时候能否提取 token 的 offset?

### ISSUE THREAD

**Issue by t-k-** [yanyiwu/cppjieba#66]
如果不能的话是否考虑加入这个功能？

**Comment by yanyiwu** [comment]
已经有这个功能的了，参见 https://github.com/yanyiwu/cppjieba/blob/master/test/demo.cpp#L50

**Comment by yanyiwu** [comment]
如果你使用的是旧版本的代码，那可能还没有该接口。
该功能是自从 [v4.7.0](https://github.com/yanyiwu/cppjieba/releases/tag/v4.7.0) 开始加入的。

**Comment by t-k-** [comment]
之前我是在某个cppjieba版本看了一下没有发现，于是又花了些时间尝试用 c 调用 jieba，但总是在 index 一定时间以后出现类似死锁的现象， 而且python 跑起来真心慢。。回去试一试你的更新版本，谢谢！

**Comment by yanyiwu** [comment]
恩，有任何问题或者改进意见欢迎随时反馈哈，之前确实因为没有带位置信息的分词功能，也是经过反馈加上的。

**Comment by t-k-** [comment]
好的。分词十有八九用在搜索上，所以返回 offset 基本是属于必要功能。过程中有问题会及时向你反馈的:muscle:

**Comment by t-k-** [comment]
@yanyiwu 你好，我自己的 code 已经切换到 cppjieba，并且 index 了一个稍具规模的 corpus（0.1 M documents），暂时没有发现什么问题。
切换到 cppjieba 解决了我之前使用 C 调用 python 引起的 indexing 时间久了会死锁问题（原因不明）。但我依然有过滤标点符号的需求，不知道在 cppjieba 里面有没有比通过 tag 识别标点更高效的方法？另外，由于使用 CutForSearch 函数没有办法获得 token 的 tag，我在 #72 里做了一些修改，可以暴露一个帮助查询**单个** token tag 的 API （这样开发的人可以结合其他函数一起使用，比如 CutForSearch），若有其他方法，就请忽略这个 PR.
