### ISSUE TITLE
[求助]windows下不能正确分词

### ISSUE THREAD

**Issue by frederickMaster** [yanyiwu/cppjieba#68]
移植到了VS上，修改了编码格式为UTF-8， 设置了string默认编码为UTF-8，运行后仍无法正确显示。

他来到了网易杭研大厦
[demo] Cut With HMM
他/来/到/了/网/易/杭/研/大/厦
[demo] Cut Without HMM
他/来/到/了/网/易/杭/研/大/厦
我来到北京清华大学
[demo] CutAll
我/来/到/北/京/清/华/大/学
小明硕士毕业于中国科学院计算所，后在日本京都大学深造
[demo] CutForSearch
小/明/硕/士/毕/业/于/中/国/科/学/院/计/算/所/，/后/在/日/本/京/都/大/学/深/造
[demo] Insert User Word
男/默/女/泪
男默女泪
[demo] CutForSearch Word With Offset
[{"word": "小", "offset": 0}, {"word": "明", "offset": 2}, {"word": "硕", "offse
t": 4}, {"word": "士", "offset": 6}, {"word": "毕", "offset": 8}, {"word": "业",
 "offset": 10}, {"word": "于", "offset": 12}, {"word": "中", "offset": 14}, {"wo
rd": "国", "offset": 16}, {"word": "科", "offset": 18}, {"word": "学", "offset":
 20}, {"word": "院", "offset": 22}, {"word": "计", "offset": 24}, {"word": "算",
 "offset": 26}, {"word": "所", "offset": 28}, {"word": "，", "offset": 30}, {"wo
rd": "后", "offset": 32}, {"word": "在", "offset": 34}, {"word": "日", "offset":
 36}, {"word": "本", "offset": 38}, {"word": "京", "offset": 40}, {"word": "都",
 "offset": 42}, {"word": "大", "offset": 44}, {"word": "学", "offset": 46}, {"wo
rd": "深", "offset": 48}, {"word": "造", "offset": 50}]
[demo] Tagging
我是拖拉机学院手扶拖拉机专业的。不用多久，我就会升职加薪，当上CEO，走上人生巅峰
。
[我:x, 是:x, 拖:x, 拉:x, 机:x, 学:x, 院:x, 手:x, 扶:x, 拖:x, 拉:x, 机:x, 专:x,
业:x, 的:x, 。:x, 不:x, 用:x, 多:x, 久:x, ，:x, 我:x, 就:x, 会:x, 升:x, 职:x, 加
:x, 薪:x, ，:x, 当:x, 上:x, CEO:eng, ，:x, 走:x, 上:x, 人:x, 生:x, 巅?x, 濉?x]
[demo] Keyword Extraction
我是拖拉机学院手扶拖拉机专业的。不用多久，我就会升职加薪，当上CEO，走上人生巅峰
。
[{"word": "CEO", "offset": [62], "weight": -1.08658e+063}]

**Comment by yanyiwu** [comment]
参见： https://github.com/yanyiwu/cppjieba/issues/62
