### ISSUE TITLE
分享的词典下载地址已经挂了

### ISSUE THREAD

**Issue by willin** [yanyiwu/cppjieba#70]
```
其它词典资料分享

dict.367W.utf8.tar.gz iLife(562193561@qq.com)
```

README里

**Comment by qinwf** [comment]
这里有一份修改过的，修改了个别行的乱码。

https://github.com/qinwf/BigDict

**Comment by yanyiwu** [comment]
谢谢 @willin 提醒 和 @qinwf 的分享，我已经在 README 中把链接修改到 @qinwf 提供的那个链接。

**Comment by tx0c** [comment]
https://github.com/qinwf/BigDict is also no longer available, anyone has alternatives?
