### ISSUE TITLE
终于在vs2010里用起来了，就是加载词典消耗时间很长，不知道有没有解决办法。

### ISSUE THREAD

**Issue by zhtsky** [yanyiwu/cppjieba#77]
vs 用的GBK编码 研究了半天才搞明白

[新建文本文档.txt](https://github.com/yanyiwu/cppjieba/files/520858/default.txt)

**Comment by t-k-** [comment]
跟 vs 没关系，写程序的文本文件可以保存为 utf-8.

**Comment by zhtsky** [comment]
好像不是啊，我把cpp文件改成UTF8，vs处理的时候好像还是按GBK处理的，结果分词就是一个字一分，我转成UTF8再分词，之后再转回来就好使。直接从文件读应该是没问题。

**Comment by t-k-** [comment]
> 我把cpp文件改成UTF8

怎么改的？通过 vs "另存为"改的？

**Comment by zhtsky** [comment]
@t-k- 有个高级保存选项，用notpad++也试过了

**Comment by t-k-** [comment]
有另存为为什么不用？我就是怕你用了第三方的工具，或者自己转换。因为 vs 发现了可能还把 文件又转换回去了。。。。。

**Comment by zhtsky** [comment]
@t-k- 这样啊，不过我用的VS里的高级保存，另存为里没有编码格式。另外UTF8带签名和不带签名有关系么？改成不带签名编译通不过。谢谢大神了^_^

**Comment by t-k-** [comment]
很久没用 vs了，我不是大神，你等等其他有 vs 环境的人吧，问问他们。

**Comment by t-k-** [comment]
你可以把你保存为 utf8 的文本文件也传上来，我用 enca 帮你看看你程序里的字符串有没有真正转换成 utf8

**Comment by zhtsky** [comment]
我用notepad++查看确实显示是utf8格式了，真不理解VS是怎么工作的，不过好在写个函数手动转化一下就可以了，还是谢谢你了^_^。
另外release模式加载词典用时几百毫秒左右，基本可以接受，谢谢作者yanyiwu写出这么好的软件^_^。

**Comment by yanyiwu** [comment]
谢谢 @t-k-
