### ISSUE TITLE
python版的精确模式对应cpp版哪个模式？

### ISSUE THREAD

**Issue by dd2333** [yanyiwu/cppjieba#86]
您好，cpp版本里哪个和python版的精确模式一样，因为我这边要实现多端统一结果，把cpp版本每个都试了还是不同.

测试文本：
原标题：《中国诗词大会》武亦姝登顶，年龄最小的她如何“过关斩将”央视《中国诗词大会》第二季总决赛收官，淡定从容、“飞花令”中出口成章的武亦姝笑到了最后。

**Comment by dd2333** [comment]
查了下，感觉是HMM模型出来的结果不一样

**Comment by yaleimeng** [comment]
+ 估计不能完全对应（但差异也很小）。它们词典、模型训练的时间和语料不完全一样。
+ python版本后续更新略好些，部署生态环境也好。cpp版本只是速度快，但用户感受不太明显。
