### ISSUE TITLE
问个问题：demo 您的Makefile编译比我自己编译的快5倍

### ISSUE THREAD

**Issue by hxsnow10** [yanyiwu/cppjieba#90]
我自己就是g++ -o demo demo.cpp
计算了时间，你编译后的demo Cut运行速度快5倍

我不太懂你的Makefile，请问您用了什么参数，我用什么样的命令编译也能这么快吗？

我写了个python版本的接口，生成.so文件，我在想用你的编译方法，能让这个接口的分词速度也快5倍吗？

谢谢！

**Comment by yanyiwu** [comment]
试试 g++ -O3 -o demo demo.cpp

**Comment by hxsnow10** [comment]
可以 ！  谢谢
