### ISSUE TITLE
可不可以用visual studio2010来运行？

### ISSUE THREAD

**Issue by idychenxi** [yanyiwu/cppjieba#94]
可不可以用visual studio2010来运行？

**Comment by qinwf** [comment]
可以参考 这个 appveyor 文件，CI 测试是在 VS2015 上跑的。

https://github.com/yanyiwu/cppjieba/blob/master/appveyor.yml

https://ci.appveyor.com/project/yanyiwu/cppjieba/branch/master

**Comment by LuwangChou** [comment]
可以运行，但是一些文件需要更改为utf8 带签名（with BOM）编码.
