### ISSUE TITLE
是否考虑把字典在编译期就编进代码？

### ISSUE THREAD

**Issue by LuoZijun** [yanyiwu/cppjieba#97]
如题: 是否考虑把字典在编译期就编进代码？

这样，不需要去硬盘查找。配置啥的都方便了。

**Comment by yanyiwu** [comment]
这。。。理论上也可以。。。

**Comment by LuoZijun** [comment]
@yanyiwu 我主要是考虑移植的时候方便，比如移植到 `Rust` 。

**Comment by yanyiwu** [comment]
应该不太影响移植吧，https://github.com/qinwf/jiebaR 也是封装的cppjieba，看上去移植的挺好的。rust的包管理也很不错，应该没太影响。

**Comment by yanyiwu** [comment]
当然，有实现这个需求的pull request随时欢迎。

**Comment by fantasticfears** [comment]
C++ 把资源编译成二进制库应该要写 layout 吧？那不如就用路径查找，更简单。

**Comment by LuoZijun** [comment]
@fantasticfears @yanyiwu  

我不会 C++ ，我的 rust 实现是 使用 Python 对 训练好的数据集 按照 Rust 的类型格式生成。Rust 代码。

由于硬编译的查找表，所以使用起来还是比较方便的。内存占用也是相当低(拿围城做测试时，内存占用仅仅3.9MB)。

当然编译完后的二进制执行程序体积会有点大(跟未编码版本的内存占用类似)。

**Comment by fantasticfears** [comment]
> 我不会 C++ ，我的 rust 实现是 使用 Python脚本 对 训练好(或统计好) 的数据集(dict) 按照 Rust 的类型格式生成 Rust 代码（数据集有更新的话，重新执行这个Python脚本就好，然后对 Rust 代码重新编译）。

我完全没看懂。

内存占用很好。cppjieba 现在的 Trie tree 实现占了 ~120MB 内存。
二进制代码作大量数据的话我记得大一点的库都有做 slice，比如 ICU。不知道什么坑在里面吧。编译出来的 binary 跟语言是无关的。

**Comment by LuoZijun** [comment]
@fantasticfears 

就是:

```bash

python3 make.py -> hidden_markov_model.rs

```

**Comment by zxygentoo** [comment]
也许另一种可能的思路是把 Jieba struct 的参数从字典路径的指针改为字典实际内容的指针，这样可能有的好处

- 移植方可以比较方便的自己决定如何处理字典文件，编译进二进制文件，用自己的包格式打包，或者在运行时由用户提供，应该都比较容易实现。
- 可以方便移植到没有文件系统的环境？

只是个人想法，我既不是活跃的 C/C++ 用户，也只是简单浏览了一下 CppJieba 的实现，所以可能有片面和错误的地方。

提出这个主要是我确实碰到了相关的问题。工作上有一个分词相关的 rust bind CppJieba 的包，新的需求要把这个 rust 包以 python 扩展的形式打包成一个 Python 包（如果使用现成的 cppjieba python 包，那就还要用 python 重写不少 rust 的逻辑）。本来以目前 rust 对 python 良好的工具支持，这件事应该很容易，但因为这需要 rust 代码在运行时可以找到 python 包的安装位置（不受我控制），我还希望保持开发和发布体验一致（要让 cargo 也能够协同工作），所以最后只能做一些比较非常规的动作来达到目的。不是说特别大的问题，但感觉这个过程其实可以更无痛。

**Comment by zxygentoo** [comment]
是的。这一部分还好，让开发测试打包过程中 cargo pytest 这些都可靠和顺畅的一起联动比较烦一点😂

**Comment by zxygentoo** [comment]
我看看，谢谢推荐
